name: gdsc_bloc
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1
  firebase: ^9.0.3
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  google_sign_in: ^6.1.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  connectivity_plus: ^4.0.0
  animated_bottom_navigation_bar: ^1.2.0
  cloud_firestore: ^4.7.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  lottie: ^2.3.2
  http: ^0.13.6
  googleapis_auth: ^1.4.0
  googleapis: ^11.1.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  badges: ^3.1.1
  dropdown_button2: ^2.1.3
  photo_view: ^0.14.0
  dio: ^5.1.2
  path_provider: ^2.0.15
  awesome_notifications: ^0.6.19
  share_plus: ^7.0.1
  permission_handler: ^10.2.0
  gallery_saver: ^2.3.2
  grouped_list: ^5.1.2
  flutter_linkify: ^6.0.0
  firebase_messaging: ^14.6.2
  add_2_calendar: ^2.2.3
  flex_color_scheme: ^7.2.0
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^15.1.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  mocktail: ^0.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/logo.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
    - shorebird.yaml
